myProject/online/apps/courses/urls.py
from django.conf.urls import url
from django.urls import path


from .views import CoursesListView, CourseDetailView, CourseVideoView, CourseCommentView,VideoPlayView

urlpatterns = [
    # 课程列表
    path('list/', CoursesListView.as_view(), name='list'),

    # 课程详情
    path('detail/<int:course_id>/', CourseDetailView.as_view(), name='detail'),

    # 章节列表，点击开始学习时出现的视频列表
    path('video/<int:course_id>/', CourseVideoView.as_view(), name='video'),

    # 课程评论
    path('comment/<int:course_id>/', CourseCommentView.as_view(), name='comment'),

    # 视频播放
    path('play/<int:video_id>/', VideoPlayView.as_view(), name='play'),

]

myProject/online/apps/organizations/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


from django.conf.urls import url
from django.urls import path
from .views import TeacherListView, OrgListView, OrgHomeView, UserAskView, OrgCourseView, OrgTeacherListView, \
    OrgDescView, TeacherDetailView, AddFavView

urlpatterns = [
    # 教师列表
    path('teach_list/', TeacherListView.as_view(), name='teach_list'),

    # 教师详情
    path('teacher_detail/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail'),

    # 机构列表
    path('org_list/', OrgListView.as_view(), name='org_list'),

    # 机构首页
    path('org_home/<int:org_id>/', OrgHomeView.as_view(), name='org_home'),

    # 用户咨询
    path('user_ask/', UserAskView.as_view(), name='user_ask'),

    # 机构课程
    path('org_course/<int:org_id>/', OrgCourseView.as_view(), name='org_course'),

    # 机构教师
    path('org_teacher/<int:org_id>/', OrgTeacherListView.as_view(), name='org_teacher'),

    # 机构介绍
    path('org_desc/<int:org_id>/', OrgDescView.as_view(), name='org_desc'),

    # 收藏机构
    path('add_fav/',AddFavView.as_view(), name='add_fav'),
]

myProject/online/apps/users/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import path

from .views import RegisterView, LoginView, RegisterActiveView, UserInfoView, ForgetpwdView, PwdresetView, \
    PwdmodifyView, LogoutView, MyCourseView, MyfavOrgView, MyfavCourseView, MyfavTeacherView, MyMessageView, \
    UploadImageView, UploadPwdView, UploadUserInfoView, UpdateEmailView

urlpatterns = [
    # 用户注册
    path('register/', RegisterView.as_view(), name='register'),
    # 用户登录
    path('login/', LoginView.as_view(), name='login'),
    # 注册激活链接
    path('active/<url_active_code>/', RegisterActiveView.as_view()),
    # 个人中心
    path('userinfo/', UserInfoView.as_view(), name='userinfo'),
    # 个人中心——头像修改
    path('uploadimage/', UploadImageView.as_view(), name='uploadimage'),
    # 个人中心——密码修改
    path('uploadpwd/', UploadPwdView.as_view(), name='uploadpwd'),
    # 个人中心——基本资料修改
    path('uploadinfo/', UploadUserInfoView.as_view(), name='uploadinfo'),
    # 个人中心-修改邮箱
    path('update_email/', UpdateEmailView.as_view(), name='update_email'),
    # 我的课程
    path('mycourse/', MyCourseView.as_view(), name='mycourse'),
    # 我的收藏——机构
    path('myfavorg/', MyfavOrgView.as_view(), name='myfavorg'),
    # 我的收藏——课程
    path('myfavcourse/', MyfavCourseView.as_view(), name='myfavcourse'),
    # 我的收藏——教师
    path('myfavteacher/', MyfavTeacherView.as_view(), name='myfavteacher'),
    # 我的消息
    path('mymessage/', MyMessageView.as_view(), name='mymessage'),
    # 忘记密码
    path('forgetpwd/', ForgetpwdView.as_view(), name='forgetpwd'),
    # 重置密码链接
    path('pwdreset/<url_pwdreset_code>/', PwdresetView.as_view(), name='pwdreset'),
    # 重置密码处理
    path('pwdmodify/', PwdmodifyView.as_view(), name='pwdmodify'),
    # 注销登录/登出
    path('logout/', LogoutView.as_view(), name='logout'),

]

myProject/online/online/urls.py
from django.conf import settings
from django.views.static import serve  # 处理静态文件


from django.contrib import admin
from django.urls import path, include  # 等同于在django.conf.urls导入include
from django.conf.urls import url
import xadmin

from users.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', xadmin.site.urls),

    # 验证码路由
    path('captcha/', include('captcha.urls')),

    # 课程机构相关 URL
    path(r'org/', include(('organizations.urls', 'organizations'), namespace='org')),

    # 课程相关 URL 配置
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),

    # 用户中心 URL 配置,看include源码进行配置，默认app_name=None,只有为元组时才能传入参数
    path('users/', include(('users.urls', 'users'), namespace='users')),

]

if settings.DEBUG:
    #  配置静态文件访问处理
    urlpatterns.append(url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

# 全局页面配置
handler403 = 'users.views.page_not_look'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

myProject/online/apps/courses/models.py
# _*_ coding:utf-8 _*_
from datetime import datetime
from django.db import models
from organizations.models import Organizationinfo, Teacher


class Courseinfo(models.Model):
    """课程信息"""
    course_org = models.ForeignKey(Organizationinfo, on_delete=models.CASCADE, null=True, verbose_name='所属机构')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True, verbose_name='教师')
    name = models.CharField(max_length=100, verbose_name='课程名称')
    image = models.ImageField(verbose_name='课程封面', upload_to='courses/%Y/%m', max_length=100)
    desc = models.CharField(max_length=300, verbose_name='课程描述')
    degree_choice = (('cj', '初级'), ('zj', '中级'), ('gj', '高级'))
    degree = models.CharField(verbose_name='难度',
                              choices=degree_choice, default='cj', max_length=2)
    students = models.IntegerField(verbose_name='学习人数', default=0)
    learn_time = models.IntegerField(verbose_name='学习时长（分钟数）', default=0)
    category = models.CharField(verbose_name='课程类别',
                                default='后端', max_length=100)
    fav_nums = models.IntegerField(verbose_name='收藏人数', default=0)
    click_nums = models.IntegerField(verbose_name='点击数', default=0)
    detail = models.TextField(verbose_name='课程详情')
    is_banner = models.BooleanField(verbose_name='是否为轮播图', default=False)
    before_know = models.CharField(verbose_name='课前须知', max_length=300, default='')
    teacher_tell = models.CharField(verbose_name='老师告诉你能学到什么', max_length=300, default='')
    add_time = models.DateTimeField(verbose_name='添加时间', default=datetime.now)
    notice = models.CharField(verbose_name='课程公告', max_length=300, default='暂无公告')

    def lession_nums(self):
        """章节数"""
        return self.lession_set.count()


    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseBanner(Courseinfo):
    """
    课程轮播图，后台管理时使用两个标签，管理一个数据表，实现数据的分类管理
    """

    class Meta:
        verbose_name = '轮播课程'
        verbose_name_plural = verbose_name
        proxy = True  # 具有models功能，同时不再生成新的表


class Lession(models.Model):
    """
    章节信息，点击我要学习进入
    """
    course = models.ForeignKey(Courseinfo, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(verbose_name='章名', max_length=100)
    add_time = models.DateTimeField(verbose_name='添加时间', default=datetime.now)

    class Meta:
        verbose_name = '课程章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(models.Model):
    """小节/视频信息"""
    lession = models.ForeignKey(Lession, on_delete=models.CASCADE, verbose_name='章')
    name = models.CharField(verbose_name='小节/视频名称', max_length=100)
    url = models.URLField(verbose_name='播放地址', max_length=200, default='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4')
    learn_time = models.IntegerField(verbose_name='视频时长（分钟数）', default=0)
    add_time = models.DateTimeField(verbose_name='添加时间', default=datetime.now)

    class Meta:
        verbose_name = '小节/视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """资料下载,如课件等资料"""
    lession = models.ForeignKey(Courseinfo, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(verbose_name='资料名称', max_length=100)
    download = models.FileField(verbose_name='资料下载', upload_to='courses/resource/%Y/%m', max_length=100)
    add_time = models.DateTimeField(verbose_name='添加时间', default=datetime.now)

    class Meta:
        verbose_name = '课程资料'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

myProject/online/templates/course-video.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}章节信息{% endblock %}
{% block crumbs%}
<!--crumbs start-->
<section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>
 {% endblock %}
{% block body %}
<div id="main">

    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">&ensp;{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_time }}</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.notice }}</a> </div>
                </div>
                <div class="mod-chapters">
{#章节信息#}
                    {% for lession in lessions %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lession.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lession.video_set.all %}
                                <li>
                                    <a target="_blank" href='{% url 'courses:play' video.id %}' class="J-media-item studyvideo">{{ video.name }}
                                        <i class="study-state"></i>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
{#资料下载#}
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>

                        <ul class="downlist">
                        {% for resource in resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
{#教师提示#}
                    <div class="box mb40">
                        <h4>教师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'org:teacher_detail' course.teacher.id %}" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
                        <span class="tit">
                          <a href="{% url 'org:teacher_detail' course.teacher.id %}" target="_blank">{{ course.teacher.name }}</a>
                        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.before_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for course_list in course_lists %}
                                        <li class="curr">
                                            <a href="course-detail.html" target="_blank">
                                                <img src="{{ MEDIA_URL }}{{ course_list.image }}" alt="{{ course_list.name }}">
                                                <span class="name autowrap">{{ course_list.name }}</span>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}

myProject/online/templates/login.html
{% extends 'usersinfo_base.html' %}

{% load staticfiles %}

{% block title %} 宅家学习网登录 {% endblock %}

{% block body %}
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'index' %}"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                {% if pwdreset_msg %}
                <h2>{{ pwdreset_msg }}</h2>
                {% else %}
                <h2>帐号登录</h2>
                {% endif %}
                <form action="{% url 'users:login' %}" method="post" autocomplete="off">
                    <div class="form-group marb20 {% if login_form.username.value %} errorput {% endif %}">
                        <label>用&nbsp;户&nbsp;名</label>
{#                        <input name="username" id="username" type="text" value="{{ login_form.username.value }}" placeholder="邮箱" />#}
                        <input name="username" id="username" type="text" value="" placeholder="请输入您的邮箱地址" />
                    </div>
                    <div class="form-group marb8 {% if login_form.password.value %} errorput {% endif %}">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
{#                        <input name="password" id="password_l" type="password" value="{{ login_form.password.value }}" placeholder="请输入您的密码" />#}
                        <input name="password" id="password_l" type="password" value="" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">
                        {% if login_form.errors.items %}
                            {% for key,error in login_form.errors.items %}
                                {{ error }}
                            {% endfor %}
                        {% else %}
                            {{ msg }}
                        {% endif %}
                    </div>
                     <div class="auto-box marb38">
                        <a class="fr" href="{% url 'users:forgetpwd' %}">忘记密码？</a>
                     </div>
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                    {% csrf_token %}
                </form>
                <p class="form-p">没有在线网帐号？<a href="{% url 'users:register' %}">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

myProject/online/templates/org-detail-course.html
{% extends 'org_base.html' %}

{% load staticfiles %}

{% block title %}
机构课程
{% endblock %}

{% block custom %}
机构课程
{% endblock %}

{% block body %}

<div class="right companycenter layout" >
		<div class="head">
			<h1>机构课程</h1>
		</div>
		<div class="brief group_list">
            {% for org_course in org_courses.object_list %}
               <div class="module1_5 box">
                    <a class="comp-img-box" href="{% url 'courses:detail' org_course.id %}">

                        <img width="214" height="195" src="{{ MEDIA_URL }}{{ org_course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url 'courses:detail' org_course.id %}"><h2>{{ org_course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ org_course.learn_time }}</i></span>
                        <span class="fr">学习人数：{{ org_course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ org.name }}</span>
                         <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            {{ org_course.fav_nums }}
                        </span>
                    </div>
                </div>
            {% endfor %}

		</div>
        <div class="pageturn">
            <ul class="pagelist">
                <li class="long">
                    {% if org_courses.has_previous %}
                    <a href="?{{ org_courses.previous_page_number.querystring }}" class="prev">上一页</a>
                    {% endif %}
                </li>

                {% for page in org_courses.pages %}
                    {% if page %}
                    {% ifequal page org_courses.number %}
                      <li class="active"><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% else %}
                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {% endifequal %}
                  {% else %}
                    <li class="none"><a href="">...</a></li>
                  {% endif %}
                {% endfor %}

                {% if org_courses.has_next %}
                     <li class="long"><a href="?{{ org_courses.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
            </ul>
        </div>
</div>
{% endblock %}

myProject/online/templates/org-detail-homepage.html
{% extends 'org_base.html' %}

{% load staticfiles %}

{% block body %}


<div class="right companycenter layout grouping" >
		<div class="head">
			<h1>全部课程</h1>
			<a class="green fr more" href="{% url 'org:org_course' org.id%}">查看更多  >  </a>
		</div>
		<div class="brief group_list">
            {% for org_course in org_courses %}
                <div class="module1_5 box">
                    <a href="{% url 'courses:detail' org_course.id %}"><img width="214" src="{{ MEDIA_URL }}{{ org_course.image }}"/></a>
                    <div class="des">
                        <a href="{% url 'courses:detail' org_course.id %}"><h2>{{ org_course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ org_course.learn_time }}</i></span>
                        <span class="fr">学习人数：{{ org_course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ org.name }}</span>
                         <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            {{ org_course.fav_nums }}
                        </span>
                    </div>
                </div>

            {% endfor %}
		</div>
</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构教师</h1>
        <a class="green fr more" href="{% url 'org:org_teacher' org.id%}">查看更多  >  </a>
    </div>
    <div class="diarys">
        <div class="module5 share company-diary-box" style="padding:10px 0;">
        {% for org_teacher in org_teachers %}
            <div class="left">
                <a href="{% url 'org:teacher_detail' org_teacher.id %}"><img class="pic" src="{{ MEDIA_URL }}{{ org_teacher.image }}"/></a>
                <p>姓名：{{ org_teacher.name }}</p>
            </div>
        {% endfor %}
        </div>
    </div>



</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构介绍</h1>
        <a class="green fr more" href="{% url 'org:org_desc' org.id%}">查看更多  >  </a>
    </div>
    <p class="cont">{{ org.desc }}</p>
</div>


{% endblock %}


myProject/online/templates/register_active_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>验证失败</title>
</head>
<body>
<h1 style="text-align: center">无效链接</h1><br>
<h2 style="text-align: center"><a href="{% url 'index' %}">点击进入宅家学习网</a></h2><br>
<h2 style="text-align: center"><a href="{% url 'users:register' %}">点击进行注册</a></h2><br>
<h2 style="text-align: center"><a href="{% url 'users:login' %}">已有账户，点击登录</a></h2><br>
</body>
</html>

myProject/online/templates/register_active_sucessed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户激活成功</title>
</head>
<body>
<h1 style="text-align: center">尊敬的用户，您好，账户已激活成功！</h1><br>
<h2 style="text-align: center"><a href="{% url 'users:login' %}">请点击链接登录账户</a></h2><br>
</body>
</html>

myProject/online/templates/usercenter-fav-course.html
{% extends 'usercenter_base.html' %}

{% load staticfiles %}

{% block title %} 我的收藏 {% endblock %}

{% block custom_bread %} 我的收藏 {% endblock %}

{% block body %}
<section>
	<div class="wp list personal_list">
            <div class="left">
                <ul>
                    <li class="{% ifequal request.path|slice:'15' '/users/userinfo' %}active2{% endifequal %}"><a href="{% url 'users:userinfo' %}">个人资料</a></li>
                    <li class="{% ifequal request.path|slice:'15' '/users/mycourse' %}active2{% endifequal %}"><a href="{% url 'users:mycourse' %}">我的课程</a></li>
                    <li class="{% ifequal request.path|slice:'12' '/users/myfav' %}active2{% endifequal %}"><a href="{% url 'users:myfavorg' %}">我的收藏</a></li>
                    <li class="{% ifequal request.path|slice:'16' '/users/mymessage' %}active2{% endifequal %}">
                        <a href="{% url 'users:mymessage' %}" style="position: relative;">
                            我的消息
                        </a>
                    </li>
                </ul>
            </div>

    
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% ifequal request.path|slice:'15' '/users/myfavorg' %}active{% endifequal %}"><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li class="{% ifequal request.path|slice:'19' '/users/myfavteacher' %}active{% endifequal %}"><a href="{% url 'users:myfavteacher' %}">授课教师 </a></li>
                        <li class="{% ifequal request.path|slice:'18' '/users/myfavcourse' %}active{% endifequal %}"><a href="{% url 'users:myfavcourse' %}">公开课</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>


	</div>
</section>
{% endblock %}

myProject/online/templates/usercenter-fav-teacher.html
{% extends 'usercenter_base.html' %}

{% load staticfiles %}

{% block title %} 我的收藏 {% endblock %}

{% block custom_bread %} 我的收藏 {% endblock %}

{% block body %}
<section>
	<div class="wp list personal_list">
            <div class="left">
                <ul>
                    <li class="{% ifequal request.path|slice:'15' '/users/userinfo' %}active2{% endifequal %}"><a href="{% url 'users:userinfo' %}">个人资料</a></li>
                    <li class="{% ifequal request.path|slice:'15' '/users/mycourse' %}active2{% endifequal %}"><a href="{% url 'users:mycourse' %}">我的课程</a></li>
                    <li class="{% ifequal request.path|slice:'12' '/users/myfav' %}active2{% endifequal %}"><a href="{% url 'users:myfavorg' %}">我的收藏</a></li>
                    <li class="{% ifequal request.path|slice:'16' '/users/mymessage' %}active2{% endifequal %}">
                        <a href="{% url 'users:mymessage' %}" style="position: relative;">
                            我的消息
                        </a>
                    </li>
                </ul>
            </div>


    
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% ifequal request.path|slice:'15' '/users/myfavorg' %}active{% endifequal %}"><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li class="{% ifequal request.path|slice:'19' '/users/myfavteacher' %}active{% endifequal %}"><a href="{% url 'users:myfavteacher' %}">授课教师 </a></li>
                        <li class="{% ifequal request.path|slice:'18' '/users/myfavcourse' %}active{% endifequal %}"><a href="{% url 'users:myfavcourse' %}">公开课</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for teacher in teachers %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'org:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'org:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}
                                        {% if teacher.is_gold and teacher.is_authentication %}
                                            <span class="key picbig">金牌教师</span>
                                        {% elif teacher.is_authentication %}
                                    &ensp;&ensp;      <img src="{% static 'images/authentication.png' %}"/>
                                        {% endif %}
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_years }}</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.course_nums }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作单位：<span>{{ teacher.org.name }}</span></li>
                                    <li class="c7">工作职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>

                    {% endfor %}


                    
                </div>
            </div>
        </div>


	</div>
</section>
{% endblock %}